site_src/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('account/', include('user.urls')),
    path('', include('sneaksaver.urls')),
    path('sneakers/', include('sneakers_image_recog.urls')),
    path('', include('data_analysis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import account_setting_view

app_name="user"

urlpatterns = [
    path("settings/", account_setting_view, name="account_settings")
]

templates/snippets/affilate_ads.html
{% load static %}

<div class=" container-lg d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <div class="row featurette mt-5">

        <div class="col-12">
            <div class="container">
                <div class="h1 container fw-bold text-center">
                    <div class="affilate">
                        <div class="fs-1">SNEAKSAVERS</div>
                        <div class="">SNEAKSAVERS</div>
                    </div>
                </div>
                <p class="fs-4 mt-2">
                    Ultimately, Sneaksavers is dedicated to helping sneaker enthusiasts 
                    prolong the life of their favorite footwear. By offering professional
                     cleaning services, high-quality maintenance products, and educational 
                     resources, we aim to empower users to take better care of their sneakers 
                     and ensure that they continue to look and feel their best for years to come.
                </p>
            </div>
        </div>
        
        <div class="col-12 mb-4 mt-5">
            <div class="container card p-0">
              <img src="{% static 'images/3.jpg' %}" alt="sneak saver" class="bd-placeholder-img w-100">
            </div>
        </div>
    </div>
</div>

templates/snippets/carousel.html
{% load static %}

<section class="section container">
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">

          {% for p in product_search %}
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="{{forloop.counter}}" class="" aria-label="Slide {{forloop.counter|add:1}}"></button>
          {%endfor%}
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" aria-label="Slide 1" class="active" aria-current="true"></button>
        </div>
        <div class="carousel-inner">

          <div class="carousel-item active">
              <img class="container bd-placeholder-img" src="{% static 'images/6.jpg' %}" aria-hidden="true" focusable="false">

          </div>

          {% for products in product_search %}
            <div class="carousel-item">
                <img class="container bd-placeholder-img" src="{{products.product.image_url}}" aria-hidden="true" focusable="false">
                <div class="container" style="background-color: rgba(0, 0, 0, .2);">
                  <div class="carousel-caption text-start">
                    <h1>{{products.product.name |truncatewords:8}}</h1>
                    <p class="fs-md-6">{{products.product.description | truncatewords:20}}</p>
                    <p><a class="" href="{{products.get_absolute_url}}">Learn more</a></p>
                  </div>
                </div>
            </div>
          {% endfor %}
           

        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>

templates/snippets/email.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 class="fw-bold">Notification from Sneaksaver</h1>
    <p class="fs-3">
        Hi {{name}}! 
        You have successfully booked a {{package}} clean service scheduled for {{date}}.
    </p>
</div>
<hr>
<div class="container">
    <span>Team Sneaksaver</span>
    <span>@2024</span>
</div>
{% endblock content %}

templates/snippets/footer.html
{% load static %}


{% if faq == "True" %}
{% else %}
<div class="chat-box">
    
    <button class=" shadow text-light">
        <i class="fa-solid fa-message"></i>
    </button>
    <p class="fw-6">Need Help?</p>

</div>

<script>
    let chatboxel = document.querySelectorAll('.chat-box')
    for (let i of chatboxel){
        i.addEventListener('click', ()=>{
            window.location.href = "{% url 'faq' %}"
        })
    }
</script>
{% endif %}
<footer class="blue-bg text-light p-5">

    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm-6">
                <ul class="social_icon">
                    <li><a href="https://web.facebook.com/?_rdc=1&_rdr"><i class="fa-brands fa-facebook"></i></a></li>
                    <li><a href="https://twitter.com/i/flow/login"><i class="fa-brands fa-twitter"></i></a></li>
                    <li><a href="https://www.linkedin.com/login"><i class="fa-brands fa-linkedin"></i></a></li>
                    <li><a href="mailto:support@sneaksavers.com"><i class="fa-brands fa-google-plus"></i></a></li>
                 </ul>
            </div>
            <div class="col-sm-6">
                <form action="">
                    <div class="form-group">
                        <label for="#subscribe" class="fw-bold fs-6 py-3">Subscribe to our newsletter</label>
                        <div class="input-group mb-3">
                            <input id="subscribe" type="email" class="form-control" placeholder="Enter your email address">
                            <button class="btn btn-primary" type="button">Subscribe</span>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col fs-6">
                <ul class="list-unstyled fw-bold">
                    <li class="footer-list"><a href="{% url 'about' %}" >About us</a></li>
                    <li class="footer-list"><a href="" >Terms & Conditions</a></li>
                    <li class="footer-list"><a href="{% url 'contact' %}" >Contact Us</a></li>
                </ul>
            </div>

            <div class="col fs-6">
                <ul class="list-unstyled fw-bold">
                    <li class="footer-list"><a href="{% url "faq" %}" >FrequentlyAskedQuestion</a></li>
                    <li class="footer-list"><a href="" >How to Refer</a></li>
                    <li class="footer-list"><a href="" >Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="my-0 pt-2 text-light text-center text-small">
        <img src="{% static 'images/logo.png' %}" alt="logo" width="50">
        <p class="mb-1">© <span id="footer-date"></span> Sneaksavers</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacy</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
      </div>
</footer>

templates/snippets/header_modal.html
{% load static %}
<div class="modal" id="nav-menu" tabindex="-1" aria-labelledby="nav-menu" aria-modal="true" role="dialog">
	<div class="modal-dialog modal-fullscreen" style="height:100vh; width:70vw; color:var(--white);">
		<div class="modal-content">
			<div class="modal-header">
				{% if request.user.is_authenticated %}
					<div class="profile d-flex align-items-center">
						<div style="width: 40px;" class="d-lg-block me-3 border rounded-5">
							<img width="100%" class="rounded-5" src="{{ request.user.user_profile.image_url }}" alt="{{ reqest.user }} profile image"></div>

							<div>
								<p class="m-0 p-0 fw-bolder fs-4">{{ request.user.first_name }}
									{{ request.user.last_name }}</p>
								<p class="m-0 p-0">@{{ request.user }}</p>
							</div>
						</div>
					{% endif %}

					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<div id="sidebarMenu" class="">
						<div class="nav_head ms-auto">
							<ul class="me-auto mb-2 mb-lg-0">
								<li class="nav-item mb-4">
									<a class="navbar-brand fs-4 ms-3 underline" href="{% url 'index' %}">
										{% if request.user.is_authenticated %}
											<i class="fa fa-desktop me-2"></i>
											Dashboard
										{% else %}
											<i class="fa fa-home me-2"></i>
											Home
										{% endif %}
									</a>
								</li>

								<div class="nav-item mb-4 d-grid align-items-center mx-auto">
									<button class="btn btn-dark me-5 mode-btn" id="mode-btn" onclick="screenSwitcher(true)">
										<i class="fa-solid fa-sun me-2"></i>
										Dark theme: on
									</button>

								</div>

								<li class="nav-item mb-4">
									<a class="navbar-brand fs-4 ms-3 underline" href="{% url 'pricing' %}">
										<i class="fa-regular fa-money-bill-1"></i>
										Pricing</a>
								</li>

								<li class="nav-item mb-4">
									<a class="navbar-brand fs-4 ms-3 underline" href="{% url 'product' %}">
										<i class="fa-brands fa-product-hunt"></i>
										Product</a>
								</li>

								<li class="nav-item mb-4">
									<a class="navbar-brand fs-4 ms-3 underline" href="{% url 'booking' %}">
										<i class="fa-solid fa-calendar-days"></i>
										Booking</a>
								</li>

								{% if request.user.is_authenticated %}

									<li class="nav-item mb-4">
										<a class="navbar-brand fs-4 ms-3 underline" href="">
											<i class="fa fa-solid fa-bell me-2"></i>
											Notification</a>
									</li>

									<li class="nav-item mb-4">
										<a class="navbar-brand fs-4 ms-3" href="{% url 'user:account_settings' %}">
											<i class="fa fa-regular fa-user me-2"></i>
											User Profile</a>
									</li>

									<li class="nav-item mb-4">
										<a class="navbar-brand fs-4 ms-3" href="{% url 'account_logout' %}">
											<i class="fa-solid fa-right-from-bracket me-2"></i>
											Logout</a>
									</li>
								{% else %}

									<li class="nav-item mb-4">
										<a class="navbar-brand fs-4 ms-3" href="{% url 'account_login' %}">
											<i class="fa-solid fa-right-to-bracket me-2"></i>
											Login</a>
									</li>
									<li class="nav-item mb-4">
										<a class="navbar-brand fs-4 ms-3" href="{% url 'account_signup' %}">
											<i class="fa-solid fa-user-plus me-2"></i>
											Sign up</a>
									</li>

								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


    <style>
        .message-body{
            height: 60vh;
            overflow-y: auto;
        }
        .receiver, .sender{
            width: 80%;
            border-radius: 20px;
            color: var(--white);
			margin-top: 5px;
        }
        .receiver{
            background-color: var(--blue);
            text-align: start;
            justify-self: flex-start;
            padding: 10px;
        }
        .sender{
            background-color: var(--navy-blue);
            opacity: .9;
            text-align: end;
            justify-self: flex-end;
            padding: 10px;
        }
    </style>
	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenteredScrollable" tabindex="-1" aria-labelledby="exampleModalCenteredScrollableTitle" style="display: none;" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalCenteredScrollableTitle">Chat with an Agent</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<div class="message-body">
						<ul style="list-style-type: none;" class="d-grid" id="message-ul">
							<li class="receiver">Welcome to sneakers <br> how may I help you</li>
							{% for reply in message %}
							{% if reply.message %}
							<li class="sender">{{reply.message}}</li>
							{% endif %}

							{% if reply.agent_reply %}
							<li class="receiver">{{reply.agent_reply}}</li>
							{% endif %}
							
							{% endfor %}
						</ul>
					</div>
					{% if request.user.is_authenticated %}

					<form method="post" enctype="multipart/form-data" novalidate="" class="needs-validation" id="form-signin">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="invalid-feedback d-block form-text error-text text-danger">
								{{ form.login.errors.as_text }}
							</div>
							<div class="invalid-feedback">
								message cannot be empty!
							</div>
							<input id="input-message" type="text" name="message" class="form-control" placeholder="message" required="">
							<div class="input-group-append">
								<div class="input-group-text">
									<button class="fas fa-share" type="submit"></button>
								</div>
							</div>
							

						</div>
					</form>
						
						<script>
							let formEl = document.querySelector('#form-signin')
							let messageBody = document.querySelector('#message-ul')
							formEl.addEventListener('submit', (e)=>{
								e.preventDefault()
								if( formEl.checkValidity()){
									let formdata = new FormData(formEl)
									let csrf = '{{ csrf_token }}'
									let option = {
										method: "post",
										headers: {
											"X-CSRFToken": csrf
										},
										body: formdata
									}
									
									messageBody.insertAdjacentHTML('beforeend', `
										<li class="sender">${formdata.get('message')}</li>
									`)
									document.querySelector('#input-message').value = ""
									fetch('{% url "message_agent" %}', option)
									.then((response)=>{
										return response.json()
									})
									.then((data)=>{
										console.log(data)
										messageBody.insertAdjacentHTML('beforeend', `
											<li class="receiver">${data.bot_response}</li>
										`)
									})
									.catch((err)=>{
										console.log(err)
									})
								}
								
							})
						</script>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
						</div>
						{% else %}
						Pls click <a href="{% url 'account_login' %}">here</a> to login before chating with any of our agents
						{% endif %}

					
					</div>
					<script src="{% static 'js/form-validation.js' %}"></script>
				</div>
			</div>

			

templates/snippets/landing_page_header.html
{% load static %}


<section class="navbar-expand-md flex-md-nowrap p-0">
    {% include 'snippets/nav.html' %}
	{% include 'snippets/message.html' %}

    <section class="py-4 navbar mt-0" id="sectionHeader">
        <div class="container">
            <div class="row d-flex justify-content-center py-md-3 align-items-center">
                <!--animation background-->
                <div class="area" >
                    <ul class="circles">
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div >
                <!--animation background end-->

                <div class="row d-flex justify-content-center py-md-3 align-items-center scroll-y-top-el">
                                    
                    <div class="col-lg-6 mx-auto ">                
                        <div class="p-0 justify-self-end">
                            <h1 style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" class="text-center text-md-start h1 fw-bolder">SNEAKSAVERS</h1>
                            <p class="fs-3 mt-5 text-center text-md-start">
                                Sneaksavers is a one-stop destination for sneaker enthusiasts who want to keep their shoes in prime condition and extend their longevity. Our website provides a platform for users to access a wide range of services and products that can help maintain and enhance the appearance and lifespan of their sneakers.
                            </p>
                        </div>
                    </div>

                    <div class="col-lg-6 mt-lg-0 mt-sm-5 justify-self-end">
                        <div class=""> <!--style="background-image: url('{% static 'img/dashboard_desktop.png' %}'); background-size:cover; width:100%; height:100%;"-->
                            <div class="">
                                <img style="width: 100%; height:70%" src="{% static 'images/3.jpg' %}" alt="">
                            </div>
                        </div>
                    </div> 
                </div>
    
            </div>

            
        </div>
    </section>
<section>

templates/snippets/main_header.html
<section class="navbar-expand-md flex-md-nowrap p-0 align-items-center">
{% include 'snippets/nav.html' %}
<section>

templates/snippets/message.html
<style>
    .alert-error{
        background-color: #d86e79;
        color: #442428;
    }
</style>

<div id="msg">
    {% if messages %}
    <div class="container" class="mt-5">
    <div>
        {% for message in messages %}
        <div class="d-flex justify-content-center text-center alert alert-{{message.tags}} m-2" role="alert">
            <p class="fw-bold fs-4 mb-0 mx-2">{{message.tags | title}}!</p>
            <p class="fs-4 mb-0">{{message}}</p>
        </div>
        {% endfor %}
    </div>
    </div>
    {% endif %}
</div>

<script>
    setTimeout(function(){
        if ($('#msg').length > 0){
            $('#msg').remove();
        }
    }, 5000)
</script>

templates/snippets/nav.html
{%load static%}

<nav class="navbar blue-bg navbar-dark sticky-top">
    <a id="header-logo" class="navbar-brand col-md-3 col-lg-2 me-0 px-2 fs-4" href="{% url 'index' %}">

        <span class="navbar-brand h4">SNEAKSAVERS</span>
        <img src="{% static 'images/logo.png' %}" alt="logo" width="50">
    </a>

    <form class="d-flex mx-md-2 align-items-center me-5" method="get" action="{% url "search" %}">
        <input name="q" class="form-control" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
    </form>
    
    <div class="nav-item d-none d-md-grid align-items-center mx-auto">
        <button class="btn btn-dark me-2" id="mode-btn">
            <i class="fa-solid fa-sun"></i>
        </button>
        
    </div>

    

    <button type="button" class="navbar-toggler nav_toggle_btn mx-auto px-2 d-flex collapsed mt-3 mb-1 ms-5" data-bs-toggle="modal" data-bs-target="#nav-menu">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="" class="collapse navbar-collapse me-5">
        <div class="nav_head ms-auto">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_admin %}
                <li class="nav-item mb-4">
                    <a class="navbar-brand fs-6 ms-3" href="/admin/">Admin</a>
                </li>
                {% endif %}
                <li class="nav-item mb-4">
                    <a class="navbar-brand fs-6 ms-3" href="{% url 'index' %}"> Home</a>
                </li>
                <li class="nav-item mb-4">
                    <a class="navbar-brand fs-6 ms-3" href="{% url 'pricing' %}"> Pricing</a>
                </li>

                {% if request.user.is_authenticated %}
                
                
                <li class="nav-item mb-1">
                    <a class="navbar-brand fs-6 ms-3" href="{% url 'user:account_settings' %}">Account Settings</a>
                </li>
                <li class="nav-item mb-1">
                    <a class="navbar-brand fs-6 ms-3" href="{% url 'account_logout' %}">Logout</a>
                </li>

                <li class="nav-item mb-1">
                    <div style="width: 40px;" class="ms-3 me-5 d-none d-lg-block border rounded-5">
                        <img width="100%" class="rounded-5" src="{{request.user.user_profile.image_url}}" alt="{{reqest.user.user_profile}} profile image">
                    </div>
                </li>
                {% else %}
                <li class="nav-item mb-1">
                    <a class="navbar-brand fs-6 ms-3" href="{% url 'account_login' %}">Login</a>
                </li>
                <li class="nav-item mb-1">
                    <a class="navbar-brand fs-6 ms-3" href="{% url 'account_signup' %}">Sign up</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>